feture(#056): Added index page
TomasCB24/DTechnology pull request #58
Opened 2022-12-06 21:17 UTC by IsmaelP19

The index page has been added. The redirections have been changed all to /catalogue when it has to redirect to the catalogue. The / direction is reserved for the index page.

To my reviewers, please check that all redirections are right, I may have left some of them.

2022-12-07 19:19 UTC, migromarj requested changes
The page works fine and the layout is amazing, but you should fix the 'padding' that has two values ​​assigned.

2022-12-07 19:19 UTC, migromarj commented on static/styles/index.css
> +  padding: 10px 20px;
Padding should have only a value.

2022-12-07 20:00 UTC, IsmaelP19 commented on static/styles/index.css
> +  padding: 10px 20px;
You are right!! I'm changing it now ⏱️

2022-12-07 22:14 UTC, ezegonmac approved these changes
I think all redirects works fine. Great job 👍🏻

2022-12-08 19:12 UTC, migromarj approved these changes
Thank you for solving what I mentioned in the review. Incredible work, the page has been spectacular 😮

2022-12-08 23:47 UTC, merged